---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: golang:1.12.9
  commands:
  - go test ./...

- name: build
  image: golang:1.12.9
  commands:
  - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux

- name: publish_drone
  image: plugins/gcr
  settings:
    repo: bip-nullfem/ssb/drone
    registry: eu.gcr.io
    tags: "1.3.0"
    dockerfile: docker/Dockerfile.server.linux.amd64
    json_key:
      from_secret: gcr_credentials
  when:
    event:
    - push
    - tag

- name: publish_controller
  image: plugins/gcr
  settings:
    repo: bip-nullfem/ssb/drone-controller
    registry: eu.gcr.io
    tags: "1.3.0"
    dockerfile: docker/Dockerfile.controller.linux.amd64
    json_key:
      from_secret: gcr_credentials
  when:
    event:
    - push
    - tag

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: bip-ci-test
  when:
    status: [ success, failure ]

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
